### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by balerum03** [jessicafarias/jessicafarias.github.io#2]
Your portfolio page looks really good but it has too many elements on the page and the whole purpose of the portfolio is to let people know about your work so, they have to be able to read it as fast as possible.
Also, there are a couple of grammar errors that are worth taking a look at.

Keep it up!!

**Comment by jessicafarias** [comment]
Currently I'm working on a redesign, thanks for your comments Im appreciate it @balerum03
